### PR TITLE
fetch queues based off status

### LINKED ISSUE #36: Get all Queues for a channel
Create an API call to get all upcoming Queues for a channel. This can be used for showing a schedule.

### PR DESCRIPTION
**Pull request by Jaqito**
closes #36 

This PR Creates an API call to get all Queues for a specific channel that have a certain status.

### CODE REVIEW

**Comment by rorochaudhary** [comment]
While this is a useful query, I am unable to find the purpose when referencing this Project Plan - is there a bot command that is expected to accompany this change? The closest thing I found was a task for "showing/saving the students left in queue when office hours ended", is this PR related to that?

**Comment by Jaqito** [comment]
> While this is a useful query, I am unable to find the purpose when referencing this Project Plan - is there a bot command that is expected to accompany this change? The closest thing I found was a task for "showing/saving the students left in queue when office hours ended", is this PR related to that?

Good Point.  I intended this as helpful for the schedule. Maybe a command to get all scheduled office hours or something?

**Comment by rorochaudhary** [comment]
> > While this is a useful query, I am unable to find the purpose when referencing this Project Plan - is there a bot command that is expected to accompany this change? The closest thing I found was a task for "showing/saving the students left in queue when office hours ended", is this PR related to that?
> 
> Good Point. I intended this as helpful for the schedule. Maybe a command to get all scheduled office hours or something?

If the goal is to get all the scheduled office hours, regardless of instructor, would it be easier to just query the DB that is holding the schedule that is edited/persisted via the scheduler tab rather than gathering the scheduled queues? Something like a "show schedule" command, or just having the current schedule integrated into the tab?

**Comment by Jaqito** [comment]
Makes sense. I'll close this for now.

**Pull request closed without merging**
